function cfg = configRadarScene()
%CONFIGRADARSCENE Demo configuration for a synthetic mmWave height pipeline.

c = physconst("LightSpeed");
fcHz = 77e9;
lambdaM = c / fcHz;

cfg.inputMode = "synthetic";

cfg.radar = struct( ...
    "fcHz", fcHz, ...
    "bandwidthHz", 4e9, ...
    "chirpDurationS", 40e-6, ...
    "sampleRateHz", 12e6, ...
    "numSamples", 512, ...
    "numRangeFft", 4096, ...
    "numVirtualRx", 16, ...
    "elementSpacingM", lambdaM / 2, ...
    "lambdaM", lambdaM, ...
    "radarHeightM", 1.0);

cfg.processing = struct( ...
    "rangeLimitsM", [0.5, 6.0], ...
    "rangeRoiHalfWidthBins", 26, ...
    "angleGridDeg", -30:0.1:35, ...
    "detectionThreshold", 0.03, ...
    "strongPointThreshold", 0.10, ...
    "targetHalfWidthM", 0.35, ...
    "zLimitsM", [0.0, 2.4], ...
    "zPercentiles", [0.01, 0.99], ...
    "xImageEdgesM", 1.4:0.02:4.6, ...
    "zImageEdgesM", 0.0:0.02:2.4);

cfg.scene = struct( ...
    "clutterPoints", [ ...
        2.0, 0.0, 0.12; ...
        4.8, 1.1, 0.08; ...
        5.2, 1.8, 0.06], ...
    "measurementNoiseAmp", 0.008, ...
    "backgroundNoiseAmp", 0.004);

cfg.acceptance = struct( ...
    "maxAbsErrorM", 0.05);

cfg.demoScenarios = [ ...
    struct("label", "Case-1", "heightM", 1.60, "rangeM", 2.8, "tiltDeg", 0.0, "seed", 101, "isNominal", false), ...
    struct("label", "Case-2", "heightM", 1.72, "rangeM", 3.0, "tiltDeg", 0.5, "seed", 102, "isNominal", true), ...
    struct("label", "Case-3", "heightM", 1.80, "rangeM", 3.2, "tiltDeg", -0.5, "seed", 103, "isNominal", false)];
end
